# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Almost Random
tagline:             'because randomness is hard'
description:         'This is the personal website of Hassan Alsibyani'
url:                 https://sibyani.org
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Hassan M. Alsibyani
  url:               https://twitter.com/HSibyani
  email:             H@Sibyani.org

# Custom vars
version:             1.0.0
